#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Tue Jan 10 16:12:16 2012


import wx

# begin wxGlade: extracode
# end wxGlade



class MyFrame(wx.Frame):
	def __init__(self, *args, **kwds):
		# begin wxGlade: MyFrame.__init__
		kwds["style"] = wx.DEFAULT_FRAME_STYLE
		wx.Frame.__init__(self, *args, **kwds)
		self.window_1 = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER|wx.SP_LIVE_UPDATE)
		self.window_1_pane_2 = wx.Panel(self.window_1, -1)
		self.window_1_pane_1 = wx.Panel(self.window_1, -1, style=wx.TAB_TRAVERSAL|wx.FULL_REPAINT_ON_RESIZE)
		
		# Menu Bar
		self.frame_1_menubar = wx.MenuBar()
		wxglade_tmp_menu = wx.Menu()
		self.ClearMessage = wx.MenuItem(wxglade_tmp_menu, 0, "Clear", "Clear_Message", wx.ITEM_NORMAL)
		self.ExitProgram = wx.MenuItem(wxglade_tmp_menu, wx.ID_EXIT, "Exit", "Quit", wx.ITEM_NORMAL)
		wxglade_tmp_menu.AppendItem(self.ClearMessage)
		wxglade_tmp_menu.AppendItem(self.ExitProgram)
		self.frame_1_menubar.Append(wxglade_tmp_menu, "File")
		self.SetMenuBar(self.frame_1_menubar)
		# Menu Bar end
		self.market_data = wx.TextCtrl(self.window_1_pane_1, -1, "", style=wx.TE_PROCESS_ENTER|wx.TE_MULTILINE|wx.TE_RICH|wx.TE_LINEWRAP)
		self.sort_button = wx.Button(self.window_1_pane_1, -1, "Sort message", style=wx.BU_BOTTOM)
		self.message_tree = wx.TreeCtrl(self.window_1_pane_2, -1, style=wx.TR_HAS_BUTTONS|wx.TR_NO_LINES|wx.TR_DEFAULT_STYLE|wx.SUNKEN_BORDER|wx.TR_EDIT_LABELS)
		self.but = wx.Button(self.window_1_pane_2, -1, "Create message")

		self.__set_properties()
		self.__do_layout()

		self.Bind(wx.EVT_MENU, self.quit_app, self.ExitProgram)
		self.Bind(wx.EVT_MENU, self.clear_message, self.ClearMessage)
		# end wxGlade
		self.Bind(wx.EVT_BUTTON, self.message_sort, self.sort_button)
		self.Bind(wx.EVT_BUTTON, self.message_create, self.but)
		
	def __set_properties(self):
		# begin wxGlade: MyFrame.__set_properties
		self.SetTitle("Fix Message fixer")
		# end wxGlade

	def __do_layout(self):
		# begin wxGlade: MyFrame.__do_layout
		sizer_1 = wx.BoxSizer(wx.VERTICAL)
		sizer_3 = wx.BoxSizer(wx.VERTICAL)
		sizer_2 = wx.GridSizer(2, 1, 5, 6)
		sizer_2.Add(self.market_data, 0, wx.ALL|wx.EXPAND, 0)
		sizer_2.Add(self.sort_button, 0, wx.ALL|wx.ALIGN_BOTTOM|wx.ALIGN_CENTER_HORIZONTAL, 0)
		self.window_1_pane_1.SetSizer(sizer_2)
		sizer_3.Add(self.message_tree, 1, wx.EXPAND, 0)
		sizer_3.Add(self.but, 0, 0, 0)
		self.window_1_pane_2.SetSizer(sizer_3)
		self.window_1.SplitVertically(self.window_1_pane_1, self.window_1_pane_2)
		sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)
		self.SetSizer(sizer_1)
		sizer_1.Fit(self)
		self.Layout()
		# end wxGlade

	def quit_app(self, event): # wxGlade: MyFrame.<event_handler>
		print "Event handler `quit_app' not implemented!"
		self.Close()
	def clear_message(self, event):
		self.message_tree.DeleteAllItems()
		self.market_data.SetValue("")

	def message_sort(self, event):
		#print "Not implemented: sort message"
		#first clear the old tree
		self.message_tree.DeleteAllItems()
		
		message = self.market_data.GetValue()
		message_root = self.message_tree.AddRoot("Message")
		tags = message.split('\x01')
		for tag in tags:
			#print tag
			self.message_tree.AppendItem(message_root, tag) 
			
	def message_create(self, event):
		print "Not implemented: create message"
		message = ""
		self.market_data.SetValue("")
		message_root = self.message_tree.GetRootItem()
		first_tag, cookie = self.message_tree.GetFirstChild(message_root)
		message = self.message_tree.GetItemText(first_tag) + "\x01"
		next_tag, cookie = self.message_tree.GetNextChild(message_root, cookie)
		while next_tag.IsOk():
			message = message + self.message_tree.GetItemText(next_tag) + "\x01"
			next_tag,cookie = self.message_tree.GetNextChild(message_root, cookie)
			
		self.market_data.SetValue(message)
		
# end of class MyFrame


if __name__ == "__main__":
	app = wx.PySimpleApp(0)
	wx.InitAllImageHandlers()
	frame_1 = MyFrame(None, -1, "")
	app.SetTopWindow(frame_1)
	frame_1.Show()
	app.MainLoop()
